{% set version = "4.13" %}

package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal-swig-bindings/archive/756186a21e8c78841cdb1238644abd06798b480e.zip
  sha256: 5b595cfe6aa20a604992c86ca5bada6e2596c027cf35f18bd3a82df5c8712c55
  patches:
    - 0001-Fix-linking-with-python-in-macOS.patch

build:
  number: 1
  skip: true  # [(win and py<35)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - eigen
    - ninja  # [win]
    - swig
  host:
    - cgal-cpp {{ version }}
    - python
  run:
    - cgal-cpp {{ version }}
    - python

test:
  imports:
    - CGAL
    - CGAL.CGAL_Kernel
    - CGAL.CGAL_Triangulation_2
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
