travis:
  secure:
    BINSTAR_TOKEN: W7yxZNpEc+DYhimn/+ScFQrPHMqvchkE/y+rGtEpJeKfOZvQ/IL77CfGo0dNM2E37IGOXMX8XG4rqlpJeojbzqGMrF3Lvk4Z+0kR9GkDHt2DV3GyOHloL54EnwyOpXUMxkuYHadLfwr/MGUZls9OVJCbtiAD1YkyR+kIVX+Db3/6UldMlvRWcyg6vYwdlYsGskno9YK88oMXA/xwgRdQkjRs/MWWtiW4FpQeJZK7Dz9Zq3/JPDWRji+strBxmYeWrzuQ9JPr0ydJK/t3IYfDEZBIRK5yt6GRUgMIrvNXNcWUsqmw/4nS7x8VTVK6pc/94K0KhaqVvVCOyQ427WeXk1dG/GU0/7FBqy9LasrMdcj2Tq3ilaVAoUkMIO/f7XQDHSn1beKS0FK2j0lr24HCar6fMKgdE2xmqyLjLn581cpkTqP0/PWfZEUW6Ndc/5PVjmOrHJNKrq4MznU62e5AK+ex9sPmvnViaBTEkyAV+H55lTN2IhOer4v9iDCa1nRwP4yiJ0WG0AED0VKcQG3mkuGrxg+k8ToRS+ZZryhmU6amr5H2kSjR8wlhe0i9gjNlWW9hIFxGIMLNySxxeddfZ6k24euJA8dp26RilVhwQ9pCXqY2HfMidObX/V9f4tGJshrz8AUP1v8UvSJKauZl2imyVxzH9iKEJ3FZG2XoVAI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
