travis:
  secure:
    BINSTAR_TOKEN: heeiFj5f6Z+2Nrc61a8ND/YkoF2sXRHipOMRFz1nXCyuKhLYfCbgyqn+WlFpBjVQueN+SKws22gCyOldAlYjaMoFHbi3jxrwTfVOKmEtsXDwNPpxfmNxOBTnFcCzrxxifkrsYLV/etIsQ8Ws27UEDGBQtibD7IEf6JJ5L242/3TyUKkn8x8cFJPg3WPrBASeNH4AcqVsnhyLwiZecYErOOLdtDGbY3xOekksLckz1mnc/p15VRLtgV/sBjW6FpM/TvmHkpXsCudZUlTxapc12jurcNwQOHOrRv8+wN2m0NKgjeQbkJipwhHFVrGkkMWiQnVnzjg93STWnB8EcnDENdhW/d1xQ7ZvQXiRJgLHIT7qwHplW2RPCkqWiI7SezXyMjD2szH7P5sTjKHvuxOnNoBuIkpqM/FqsRFc98yHD0G25aDrImAUfdNxGoJbgKsMdsVQj77UO3EIbzlBT5TRt0Kb62wIXUazF3p9eg5J9KDlVlGD+/DSoBVtp1LM09BGKTwhGxCsqVo4Q3rumjl3oRa+nQHr8oabdFr5ua4xtCh1K37FUSXhHbjWpOwAbn+VS1HDWXSmnfGNJEnvO3f066sFXW8vRlYeUfpGVYsEAEpHrnr5velknxXQbL+AKa/fGDZ3u1mIkZAtt6BMR+j+blC9IJMMO8v3fpTK0XYxhxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
