travis:
  secure:
    BINSTAR_TOKEN: ALlkMj57JgJIG6PnezwwqclG1yX2gNOaLsuARvfoZhjVaNqqgLxCeayNL1/a+q65xcEDC0zx0RYl/iSqeBsSyWrKdXjCU7VNXH0im7tT96qIoGZ6+DxD/eWfN2yTP638KMXa3+RcNFkzym1edp5fkJhg68jRM1z1vSDLXRVtByk/66Q1VigG+T2/nW4v9gj/7IoyczqSDF2/m5IksIkUqoylikj9HUWwJhx3uj58D+Fk1brtiICRpi/P8RSqB3G/yqL+ELMXBhx1JFQsM/s5rnRpxM0MwwAB0E3+ICYrNxjWJefpUYiNAzJ3Q9DYoVpuNzqwevrDYOKUprFZ7r89YUHLE8qiH0kESXE70bRmeaCc12jhMWNj1xfpDBckw0REsXHy+txblkMaK3wgEv11h/eDXbzgKShirdBL+bKNrmlzk/LGvZV/VccGw1I5tDYuoSmNp/c6fdTBngTEwhWMuH2cBwgNAW/ph3DG6r19Foik1oQAVFViLWVPDLtZ+nEMwUac18K5ZJif+pa7zuZ5SdOUsbP0WFCLe5Wb7hcBRsIUrrCInypMHthvTGvF09dCL1OfKc5BQloFx8zzrrerHVAVj+/xHazfYAok+Z5svAh6dCj6qoMwhhI1ZZcX1HLSYH9211RXuIXw0rZ/oUklykSPeVg0TwTBireYS+q6p80=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
